# 참고 : https://github.com/adityatelange/hugo-PaperMod/wiki/Variables

# 기본 도메인 주소 : 차후 정적파일이나 소스파일 등의 기본경로가 됨
baseUrl: "https://leaf-nam.github.io"
home:
  permalink: "https://leaf-nam.github.io"

# 해당 페이지의 기본 제목
title: "Leaf, waiting for Spring"

# 페이지네이션
paginate: 5

# 테마 설정가능 : https://themes.gohugo.io/
theme: ["PaperMod"]

# SEO(검색엔진 최적화)
enableRobotsTXT: true

# sitemap 생성
sitemap:
  changefreq: "monthly" # always, hourly daily, weekly, monthly, yearly, never
  filename: "sitemap.xml"
  priority: 0.5

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-9PNFP00SSG

# 이모지 사용가능여부
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

# 블로그 글 검색기능 사용
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

defaultContentLanguage: ko
languages:
  ko:
    languageName: ":ko:"
    weight: 1
    title: "봄을 기다리는 낙엽"
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: 아카이브
          url: /archives/
          weight: 10
        - name: 카테고리
          url: /categories/
          weight: 10
        - name: 검색
          url: /search/
          weight: 10
        - name: 알고리즘
          url: /cote/
          weight: 10
        - name: 미세팁
          url: /tips/
          weight: 10
        - name: 책 리뷰
          url: /review/
          weight: 10
        - name: 태그
          url: /tags/
          weight: 20
        - identifier: git
          name: Git
          url: https://github.com/leaf-nam/blog
          weight: 30
        - name: 게시글
          url: /posts/
          weight: 10

# 해당 변수들은 페이지 단위로도 설정 가능
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  description: "봄을 기다리는 낙엽의 기술 블로그"

  DateFormat: "2006. 1. 2."

  mainSections:
    - posts
    - concept
    - tips
    - cote
    - review

  # dark, light
  defaultTheme: auto

  # dark <-> light 토글
  disableThemeToggle: false

  # 읽는데 걸리는시간 표시
  ShowReadingTime: true

  # 단어 개수 표시
  ShowWordCount: true

  # 공유버튼 표시
  ShowShareButtons: true

  # 이전, 다음버튼 표시
  ShowPostNavLinks: true

  # 포스팅 경로 표시(foo>bar>bas)
  ShowBreadCrumbs: true

  # 코드 카피버튼(shortcode)
  ShowCodeCopyButtons: true

  ShowRssButtonInSectionTermList: true

  disableSpecial1stPost: false

  # 맨위로 스크롤버튼 사용여부
  disableScrollToTop: false

  # 댓글 사용여부(with utterances)
  comments: true

  # 메타데이터(위에 설정한 값들) 표시여부
  hidemeta: false

  # 요약 표시여부(제목 밑에 요약해서 나옴)
  hideSummary: false

  # ToC(Table of Contents; 목차) 표시여부
  UseHugoToc: true
  showtoc: true
  tocopen: true

  customCSS:
    - css/extended/custom.css

  assets:
    disableHLJS: false # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.svg"
    # favicon16x16: "/icon/favicon-16x16.png"
    # favicon32x32: "/icon/favicon-32x32.png"
    # apple_touch_icon: "/icon/apple-touch-icon.png"
    # safari_pinned_tab: "/icon/safari-pinned-tab.svg"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  label:
    text: "LEAF"

  # profile mode
  profileMode:
    enabled: true
    title: "낙엽의 블로그" # optional default will be site title
    subtitle: >
      **백엔드 개발자**입니다.

      > 🍃 장교로 복무하다가 개발이 좋아 전역했습니다. 


      > 🍃 객체지향과 TDD에 관심이 많습니다.


      > 🍃 소통과 문서화를 중요하게 생각합니다.


      > 📧 [contact : spearoad15@gmail.com](https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=spearoad15@gmail.com)
    imageUrl: "logo.png" # optional
    imageTitle: "leaf" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: 게시글
        url: "/posts"
      - name: 알고리즘
        url: "/cote"
      - name: 미세팁
        url: "/tips"
      - name: 책 리뷰
        url: "/review"
      - name: 검색
        url: "/search"
      - name: 카테고리
        url: "/categories"
      - name: 태그
        url: "/tags"
      - name: 아카이브
        url: "/archives"
      - name: Github
        url: "https://github.com/"

  # home-info mode
  # homeInfoParams:
  #   Title: "낙엽의 블로그 🍃"
  #   Content: >
  #     Leaf, waiting for Spring | 봄을 기다리는 낙엽

  #     > - **봄**을 찾아 군에서 세상밖으로 나온 **백엔드 개발자**입니다.

  #     > - 많은 사람들에게 쓰임과 도움이 된다면 그걸로 좋습니다.

  socialIcons:
    - name: github
      url: "https://github.com/leaf-nam"
    - name: gmail
      url: "https://mail.google.com/mail/?view=cm&amp;fs=1&amp;to=spearoad15@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "l76eAEMadEn1QzS8fLTbrl8ppayZprvV3uuAbMGSy_c"
    bing:
      SiteVerificationTag: "XYZabc"
    naver:
      SiteVerificationTag: "adff811404d441495a954e30579f40297ba14f5e"

  editPost:
    URL: "https://github.com/leaf-nam/blog/blob/main/content"
    Text: "Source Page" # edit text
    appendFilePath: true # to append file path to Edit link

  canonicalURL:
    URL: "https://leaf-nam.github.io"
    appendFilePath: true

  # 검색기능 옵션 : https://fusejs.io/api/options.html 참고
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # https://www.fusejs.io/api/methods.html#search 참고
    keys: ["title", "permalink", "summary", "content"]

  # 작성자 정보 추가
  author:
    email: spearoad15@gmail.com
    name: Sangyeop Nam

# Read: https://gohugo.io/getting-started/configuration-markup/#highlight
pygmentsUseClasses: true
markup:
  _merge: none
  defaultMarkdownHandler: goldmark
  goldmark:
    duplicateResourceFiles: false
    extensions:
      cjk:
        eastAsianLineBreaks: false
        eastAsianLineBreaksStyle: simple
        enable: false
        escapedSpace: false
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      passthrough:
        delimiters:
          block: []
          inline: []
        enable: false
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: "&rsquo;"
        disable: false
        ellipsis: "&hellip;"
        emDash: "&mdash;"
        enDash: "&ndash;"
        leftAngleQuote: "&laquo;"
        leftDoubleQuote: "&ldquo;"
        leftSingleQuote: "&lsquo;"
        rightAngleQuote: "&raquo;"
        rightDoubleQuote: "&rdquo;"
        rightSingleQuote: "&rsquo;"
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderHooks:
      image:
        enableDefault: false
      link:
        enableDefault: false
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
